version: 0.1

phases:
  install:
      commands:
      - echo installing ...
      - npm install

  pre_build:
    commands:
    - echo running pre build 

  build:
    commands:
        - echo Build started

  post_build:
      commands:
          - echo build completed 

artifacts:
  files:
    - '**/*'




    