version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 14
      commands:
      - echo installing ...

  pre_build:
    commands:
    - echo running pre build 
    - npm install

  build:
    commands:
        - echo Build started

  post_build:
      commands:
          - echo build completed 

artifacts:
  files:
    - '**/*'




    